/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRapidapiFacebookRouteImport } from './routes/_authenticated/rapidapi-facebook'
import { Route as AuthenticatedNoticiasRouteImport } from './routes/_authenticated/noticias'
import { Route as AuthenticatedFacebookRouteImport } from './routes/_authenticated/facebook'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCorreosRouteImport } from './routes/_authenticated/correos'
import { Route as AuthenticatedContentAiRouteImport } from './routes/_authenticated/content-ai'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRapidapiFacebookRoute =
  AuthenticatedRapidapiFacebookRouteImport.update({
    id: '/rapidapi-facebook',
    path: '/rapidapi-facebook',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNoticiasRoute = AuthenticatedNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacebookRoute = AuthenticatedFacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCorreosRoute = AuthenticatedCorreosRouteImport.update({
  id: '/correos',
  path: '/correos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContentAiRoute = AuthenticatedContentAiRouteImport.update({
  id: '/content-ai',
  path: '/content-ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/content-ai': typeof AuthenticatedContentAiRoute
  '/correos': typeof AuthenticatedCorreosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/facebook': typeof AuthenticatedFacebookRoute
  '/noticias': typeof AuthenticatedNoticiasRoute
  '/rapidapi-facebook': typeof AuthenticatedRapidapiFacebookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/content-ai': typeof AuthenticatedContentAiRoute
  '/correos': typeof AuthenticatedCorreosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/facebook': typeof AuthenticatedFacebookRoute
  '/noticias': typeof AuthenticatedNoticiasRoute
  '/rapidapi-facebook': typeof AuthenticatedRapidapiFacebookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/content-ai': typeof AuthenticatedContentAiRoute
  '/_authenticated/correos': typeof AuthenticatedCorreosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/facebook': typeof AuthenticatedFacebookRoute
  '/_authenticated/noticias': typeof AuthenticatedNoticiasRoute
  '/_authenticated/rapidapi-facebook': typeof AuthenticatedRapidapiFacebookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clientes'
    | '/content-ai'
    | '/correos'
    | '/dashboard'
    | '/facebook'
    | '/noticias'
    | '/rapidapi-facebook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/clientes'
    | '/content-ai'
    | '/correos'
    | '/dashboard'
    | '/facebook'
    | '/noticias'
    | '/rapidapi-facebook'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_authenticated/clientes'
    | '/_authenticated/content-ai'
    | '/_authenticated/correos'
    | '/_authenticated/dashboard'
    | '/_authenticated/facebook'
    | '/_authenticated/noticias'
    | '/_authenticated/rapidapi-facebook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rapidapi-facebook': {
      id: '/_authenticated/rapidapi-facebook'
      path: '/rapidapi-facebook'
      fullPath: '/rapidapi-facebook'
      preLoaderRoute: typeof AuthenticatedRapidapiFacebookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/noticias': {
      id: '/_authenticated/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof AuthenticatedNoticiasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facebook': {
      id: '/_authenticated/facebook'
      path: '/facebook'
      fullPath: '/facebook'
      preLoaderRoute: typeof AuthenticatedFacebookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/correos': {
      id: '/_authenticated/correos'
      path: '/correos'
      fullPath: '/correos'
      preLoaderRoute: typeof AuthenticatedCorreosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-ai': {
      id: '/_authenticated/content-ai'
      path: '/content-ai'
      fullPath: '/content-ai'
      preLoaderRoute: typeof AuthenticatedContentAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedContentAiRoute: typeof AuthenticatedContentAiRoute
  AuthenticatedCorreosRoute: typeof AuthenticatedCorreosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFacebookRoute: typeof AuthenticatedFacebookRoute
  AuthenticatedNoticiasRoute: typeof AuthenticatedNoticiasRoute
  AuthenticatedRapidapiFacebookRoute: typeof AuthenticatedRapidapiFacebookRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedContentAiRoute: AuthenticatedContentAiRoute,
  AuthenticatedCorreosRoute: AuthenticatedCorreosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFacebookRoute: AuthenticatedFacebookRoute,
  AuthenticatedNoticiasRoute: AuthenticatedNoticiasRoute,
  AuthenticatedRapidapiFacebookRoute: AuthenticatedRapidapiFacebookRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
