name: Deploy Backoffice (React SPA)

on:
  push:
    branches: [main]
    paths:
      - 'packages/dash-coyote/**'
      - '.github/workflows/deploy-backoffice.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Runner IP
        id: ip
        run: echo "runner_ip=$(curl -s https://api.ipify.org)" >> $GITHUB_OUTPUT

      - name: Add Runner IP to Security Group
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.runner_ip }}/32 \
            --region ${{ secrets.AWS_REGION }} || echo "Rule might already exist"

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'packages/dash-coyote/yarn.lock'

      - name: Install dependencies
        working-directory: packages/dash-coyote
        run: yarn install --frozen-lockfile

      - name: Build application
        working-directory: packages/dash-coyote
        run: yarn build
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Create deployment package
        working-directory: packages/dash-coyote
        run: |
          tar -czf backoffice-deploy.tar.gz dist

      - name: Copy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "packages/dash-coyote/backoffice-deploy.tar.gz"
          target: "/tmp/"
          strip_components: 2

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            # Extract deployment
            cd /var/www/noticias-pachuca/packages/dash-coyote
            tar -xzf /tmp/backoffice-deploy.tar.gz

            echo "✅ Backoffice deployment successful (static files)"

      - name: Remove Runner IP from Security Group
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.runner_ip }}/32 \
            --region ${{ secrets.AWS_REGION }} || echo "Rule already removed"
