name: Deploy Frontend (TanStack Start)

on:
  push:
    branches: [main]
    paths:
      - 'packages/public-noticias/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Runner IP
        id: ip
        run: echo "runner_ip=$(curl -s https://api.ipify.org)" >> $GITHUB_OUTPUT

      - name: Add Runner IP to Security Group
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.runner_ip }}/32 \
            --region ${{ secrets.AWS_REGION }} || echo "Rule might already exist"

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.20.0'
          cache: 'yarn'
          cache-dependency-path: 'packages/public-noticias/yarn.lock'

      - name: Install dependencies
        working-directory: packages/public-noticias
        run: yarn install --frozen-lockfile

      - name: Build application
        working-directory: packages/public-noticias
        run: yarn build
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Create deployment package
        working-directory: packages/public-noticias
        run: |
          tar -czf frontend-deploy.tar.gz dist package.json yarn.lock

      - name: Copy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "packages/public-noticias/frontend-deploy.tar.gz"
          target: "/tmp/"
          strip_components: 2

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            # Load NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Extract deployment
            cd /var/www/noticias-pachuca/packages/public-noticias
            tar -xzf /tmp/frontend-deploy.tar.gz

            # Install dependencies
            yarn install --frozen-lockfile

            # Update .env
            echo "${{ secrets.FRONTEND_ENV }}" > .env

            # Reload with PM2
            pm2 reload /var/www/noticias-pachuca/ecosystem.config.js --only public-noticias || pm2 start /var/www/noticias-pachuca/ecosystem.config.js --only public-noticias

            # Health check
            sleep 15
            curl -f http://localhost:3000 || exit 1

            echo "✅ Frontend deployment successful"

      - name: Remove Runner IP from Security Group
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.runner_ip }}/32 \
            --region ${{ secrets.AWS_REGION }} || echo "Rule already removed"
